# Generated by Django 5.1.4 on 2024-12-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_id_product_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='percent',
            field=models.IntegerField(default=100),
        ),
    ]
