# Generated by Django 5.1.4 on 2024-12-19 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
