# Generated by Django 5.1.4 on 2024-12-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cur_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='percent',
            field=models.IntegerField(default=100),
        ),
    ]
